import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { ArrowRight, ArrowLeft, Check, Link as LinkIcon, Image as ImageIcon, Sparkles } from "lucide-react";
import { BrandExtractor } from "./BrandExtractor";
import { MultiImageUploader } from "./MultiImageUploader";
import { VariationGenerator } from "./VariationGenerator";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

const STEPS = [
  {
    id: 1,
    title: "Extraction Automatique",
    description: "Entrez votre URL - Le système analyse automatiquement votre produit",
    icon: LinkIcon,
  },
  {
    id: 2,
    title: "Images de Référence (Optionnel)",
    description: "Uploadez 1-3 images de votre produit pour personnaliser davantage",
    icon: ImageIcon,
  },
  {
    id: 3,
    title: "Génération & Sélection",
    description: "Choisissez parmi 5 variations générées automatiquement",
    icon: Sparkles,
  },
];

interface SimpleWorkflowProps {
  productData: {
    productName: string;
    niche: string;
    description: string;
    platform: string;
    price: string;
    benefits?: string;
  };
  onComplete: (data: {
    brandData?: any;
    productImages?: string[];
    selectedVariation?: string;
    enrichedProductData?: any;
  }) => void;
}

export function SimpleWorkflow({ productData, onComplete }: SimpleWorkflowProps) {
  const [currentStep, setCurrentStep] = useState(1);
  const [brandData, setBrandData] = useState<any>(null);
  const [productImages, setProductImages] = useState<string[]>([]);
  const [selectedVariation, setSelectedVariation] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [editableData, setEditableData] = useState<any>(null);

  const progress = (currentStep / STEPS.length) * 100;

  const handleNext = () => {
    if (currentStep < STEPS.length) {
      setCurrentStep(currentStep + 1);
    } else {
      // Complete workflow with enriched product data
      const enrichedData = {
        ...productData,
        productName: brandData?.productName || productData.productName,
        niche: brandData?.niche || productData.niche,
        description: brandData?.description || productData.description,
        price: brandData?.price || productData.price,
        productType: brandData?.productType,
        features: brandData?.productFeatures?.join(", "),
        benefits: brandData?.productBenefits?.join(", "),
        keywords: brandData?.keywords?.join(", "),
        colors: brandData?.colors,
      };
      
      onComplete({
        brandData,
        productImages,
        selectedVariation: selectedVariation || undefined,
        enrichedProductData: enrichedData,
      });
    }
  };

  const handleBack = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1);
    }
  };

  const canProceed = () => {
    switch (currentStep) {
      case 1:
        return brandData !== null && !showPreview; // Brand extraction is required and preview must be confirmed
      case 2:
        return true; // Product images are optional
      case 3:
        return selectedVariation !== null; // Must select a variation
      default:
        return false;
    }
  };

  // Auto-generate variations when brand data is extracted
  const handleBrandExtracted = (data: any) => {
    setBrandData(data);
    
    // Prepare editable data for preview
    setEditableData({
      productName: data.productName || data.companyName || "",
      niche: data.niche || "beaute",
      description: data.description || "",
      price: data.price || "",
      productType: data.productType || "",
      productFeatures: data.productFeatures || [],
      productBenefits: data.productBenefits || [],
      keywords: data.keywords || [],
      colors: data.colors || [],
      targetMarket: data.targetMarket || "Marché africain",
    });
    
    setShowPreview(true);
    toast.success("Données extraites ! Vérifiez et modifiez si nécessaire.");
  };

  const handleConfirmPreview = () => {
    // Update brandData with edited values
    setBrandData(editableData);
    setShowPreview(false);
    setAutoGenerated(true);
    toast.success("Données confirmées ! Vous pouvez maintenant continuer.");
  };

  const CurrentStepIcon = STEPS[currentStep - 1].icon;

  return (
    <div className="space-y-6">
      {/* Progress Header */}
      <Card>
        <CardHeader className="pb-4">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-full bg-primary/10">
                <CurrentStepIcon className="h-6 w-6 text-primary" />
              </div>
              <div>
                <CardTitle className="text-xl">
                  Étape {currentStep}/{STEPS.length}: {STEPS[currentStep - 1].title}
                </CardTitle>
                <CardDescription className="mt-1">
                  {STEPS[currentStep - 1].description}
                </CardDescription>
              </div>
            </div>
            <Badge variant="outline" className="text-sm">
              {Math.round(progress)}% complété
            </Badge>
          </div>
          <Progress value={progress} className="h-2" />
        </CardHeader>
      </Card>

      {/* Step Content */}
      <div className="min-h-[400px]">
        {currentStep === 1 && !showPreview && (
          <BrandExtractor onBrandExtracted={handleBrandExtracted} />
        )}

        {currentStep === 1 && showPreview && editableData && (
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="h-5 w-5" />
                Prévisualisation et Édition
              </CardTitle>
              <CardDescription>
                Vérifiez et modifiez les données extraites avant de continuer
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="edit-name">Nom du produit *</Label>
                  <Input
                    id="edit-name"
                    value={editableData.productName}
                    onChange={(e) => setEditableData({...editableData, productName: e.target.value})}
                    placeholder="Nom du produit"
                  />
                </div>
                <div>
                  <Label htmlFor="edit-price">Prix</Label>
                  <Input
                    id="edit-price"
                    value={editableData.price}
                    onChange={(e) => setEditableData({...editableData, price: e.target.value})}
                    placeholder="Ex: 5000 FCFA"
                  />
                </div>
              </div>
              
              <div>
                <Label htmlFor="edit-desc">Description du produit *</Label>
                <Textarea
                  id="edit-desc"
                  value={editableData.description}
                  onChange={(e) => setEditableData({...editableData, description: e.target.value})}
                  rows={4}
                  placeholder="Description détaillée du produit"
                />
              </div>

              <div>
                <Label htmlFor="edit-type">Type de produit</Label>
                <Input
                  id="edit-type"
                  value={editableData.productType}
                  onChange={(e) => setEditableData({...editableData, productType: e.target.value})}
                  placeholder="Ex: Cosmétique, Électronique, etc."
                />
              </div>

              {editableData.productFeatures && editableData.productFeatures.length > 0 && (
                <div>
                  <Label>Caractéristiques principales</Label>
                  <div className="mt-2 space-y-2">
                    {editableData.productFeatures.map((feature: string, idx: number) => (
                      <div key={idx} className="flex gap-2">
                        <Input
                          value={feature}
                          onChange={(e) => {
                            const newFeatures = [...editableData.productFeatures];
                            newFeatures[idx] = e.target.value;
                            setEditableData({...editableData, productFeatures: newFeatures});
                          }}
                        />
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {editableData.colors && editableData.colors.length > 0 && (
                <div>
                  <Label>Couleurs de la marque</Label>
                  <div className="flex gap-2 mt-2 flex-wrap">
                    {editableData.colors.map((color: string, idx: number) => (
                      <div key={idx} className="flex flex-col items-center gap-1">
                        <div
                          className="w-12 h-12 rounded border-2 border-border shadow-sm"
                          style={{ backgroundColor: color }}
                        />
                        <span className="text-xs font-mono">{color}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              <div className="flex gap-2 pt-4">
                <Button 
                  onClick={() => {
                    setShowPreview(false);
                    setEditableData(null);
                    setBrandData(null);
                  }} 
                  variant="outline" 
                  className="flex-1"
                >
                  Annuler
                </Button>
                <Button 
                  onClick={handleConfirmPreview} 
                  className="flex-1"
                  disabled={!editableData.productName || !editableData.description}
                >
                  <Check className="mr-2 h-4 w-4" />
                  Confirmer et Continuer
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {currentStep === 2 && (
          <MultiImageUploader
            onImagesUploaded={(images) => {
              setProductImages(images);
            }}
            maxImages={3}
            minImages={1}
          />
        )}

        {currentStep === 3 && (
          <VariationGenerator
            productData={{
              // Use extracted brand data as primary source
              productName: brandData?.productName || productData.productName || "Produit",
              niche: brandData?.niche || productData.niche || "beaute",
              description: brandData?.description || productData.description || "Produit de qualité",
              platform: productData.platform || "instagram",
              price: brandData?.price || productData.price || "Prix sur demande",
              benefits: brandData?.productBenefits?.join(", ") || productData.benefits,
              productType: brandData?.productType,
              features: brandData?.productFeatures?.join(", "),
              keywords: brandData?.keywords?.join(", "),
              colors: brandData?.colors,
            }}
            onVariationSelected={(imageUrl) => {
              setSelectedVariation(imageUrl);
            }}
            numberOfVariations={5}
            autoGenerate={autoGenerated}
          />
        )}
      </div>

      {/* Navigation */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex items-center justify-between">
            <Button
              variant="outline"
              onClick={handleBack}
              disabled={currentStep === 1}
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Retour
            </Button>

            <div className="flex gap-2">
              {STEPS.map((step) => (
                <div
                  key={step.id}
                  className={`h-2 w-2 rounded-full transition-colors ${
                    step.id <= currentStep ? "bg-primary" : "bg-muted"
                  }`}
                />
              ))}
            </div>

            <Button
              onClick={handleNext}
              disabled={!canProceed()}
            >
              {currentStep === STEPS.length ? (
                <>
                  <Check className="mr-2 h-4 w-4" />
                  Terminer
                </>
              ) : (
                <>
                  Suivant
                  <ArrowRight className="ml-2 h-4 w-4" />
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
