import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

// Purge any old workbox precaches safely
cleanupOutdatedCaches();

// Precaching all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Always fetch fresh HTML from network first when online for instant deployment updates
registerRoute(
  new NavigationRoute(
    new NetworkFirst({
      cacheName: 'ecomfy-html-navigations',
      networkTimeoutSeconds: 3,
    })
  )
);

self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    
    const title = payload.title || '💰 Nouvelle commande Ecomfy';
    const body = payload.body || "Une nouvelle commande vient d'arriver.";
    const icon = payload.icon || '/app-icon-512.png';
    const badge = payload.badge || '/app-icon-512.png';
    const url = payload.url || '/';
    const orderId = payload.order_id || Date.now().toString();
    const customerPhone = payload.customer_phone || "";

    const actions = [];
    if (customerPhone) {
      actions.push({ action: 'call', title: '📞 Appeler le client' });
    }
    actions.push({ action: 'open', title: 'Ouvrir la commande' });

    event.waitUntil(
      self.registration.showNotification(title, {
        body,
        icon,
        badge,
        tag: `ecomfy-order-${orderId}`,
        data: { url, order_id: orderId, customer_phone: customerPhone },
        requireInteraction: true,
        vibrate: [300, 80, 300, 80, 700], // Cash register sound vibration pattern
        renotify: false,
        silent: false,
        actions
      }).then(() => {
        // Notify any open page so it can play the Ecomfy cash sound in foreground.
        return self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((cs) => {
          cs.forEach((c) => c.postMessage({ type: 'ecomfy-new-order', order_id: orderId }));
        });
      })
    );
  } catch (error) {
    console.error('[SW] Error parsing push payload', error);
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const data = event.notification.data || {};
  const url = data.url || '/';
  
  if (event.action === 'call' && data.customer_phone) {
    event.waitUntil(
      clients.openWindow(`tel:${data.customer_phone}`)
    );
    return;
  }

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((cs) => {
      for (const c of cs) {
        if (c.url.includes(url) && 'focus' in c) {
          return c.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(url);
      }
    })
  );
});
