// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-my-shops.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_shops_default = defineTool({
  name: "list_my_shops",
  title: "List my shops",
  description: "List the e-commerce shops that belong to the signed-in VisualPro user. Returns id, business_name, slug and creation date.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of shops to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("shops").select("id, business_name, slug, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { shops: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-shop-products.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_shop_products_default = defineTool2({
  name: "list_shop_products",
  title: "List shop products",
  description: "List products for a given shop owned by the signed-in user. Returns name, price, stock and publication state.",
  inputSchema: {
    shop_id: z2.string().uuid().describe("The shop id returned by list_my_shops."),
    limit: z2.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ shop_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: shop, error: shopErr } = await sb.from("shops").select("id").eq("id", shop_id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (shopErr) return { content: [{ type: "text", text: shopErr.message }], isError: true };
    if (!shop) return { content: [{ type: "text", text: "Shop not found or not yours" }], isError: true };
    const { data, error } = await sb.from("products").select("id, name, slug, price, compare_at_price, stock_quantity, is_published, is_featured, category, created_at").eq("shop_id", shop_id).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-shop-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_shop_orders_default = defineTool3({
  name: "list_shop_orders",
  title: "List shop orders",
  description: "List recent orders for a shop owned by the signed-in user. Filter by payment_status or order_status.",
  inputSchema: {
    shop_id: z3.string().uuid().describe("The shop id returned by list_my_shops."),
    limit: z3.number().int().min(1).max(100).default(20),
    payment_status: z3.enum(["pending", "paid", "failed", "refunded"]).optional(),
    order_status: z3.enum(["pending", "processing", "shipped", "delivered", "cancelled"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ shop_id, limit, payment_status, order_status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: shop } = await sb.from("shops").select("id").eq("id", shop_id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (!shop) return { content: [{ type: "text", text: "Shop not found or not yours" }], isError: true };
    let q = sb.from("orders").select("id, order_number, customer_name, customer_phone, total, payment_method, payment_status, order_status, created_at, products_summary").eq("shop_id", shop_id).order("created_at", { ascending: false }).limit(limit);
    if (payment_status) q = q.eq("payment_status", payment_status);
    if (order_status) q = q.eq("order_status", order_status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dqlbmtkaamjohgbcjwtw";
var mcp_default = defineMcp({
  name: "visualpro-mcp",
  title: "VisualPro",
  version: "0.1.0",
  instructions: "Tools for VisualPro shop owners. Use `list_my_shops` first to discover the signed-in user's shops, then `list_shop_products` or `list_shop_orders` with the returned shop id. All tools are read-only.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_shops_default, list_shop_products_default, list_shop_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
